### ISSUE TITLE
IOT not showing in wallet even though helium tracker and geek shows the hotspot has earned IOT

### ISSUE THREAD

**Issue by Australian-Hnt-collectors** [helium/oracles#563] opened 2023-05-12 05:44 UTC
IOT is not showing as claimable in the wallet against hotsopts in this case Wild Chambray Octopus. 

as per screen shots, IOT is not showing as claimable in the wallet against the name WILD CHAMBRAY OCTOPUS although helium tracker and others are showing the hotspot earned 450 iot average a day as per the screen shots, the helium tracker screen shot is a total for the last 10 days of iot for the single hotspot but as you see next to the name the amount is empty.  
THE APP is the latest app of 03rd May 2023 and i have logged out and back in
the SWAPPED HNT to iot then back to HNT was done to show people how to SWAP HNT TO IOT AND visa versa. and no IOT has been claimed for a number of days
![346028265_824228159408878_8808543735378350617_n](https://github.com/helium/wallet-app/assets/84670450/7d75ad65-7de4-45ed-bb73-fe235f1fdf1d)
![345997807_1703918610064500_1477318431659989483_n](https://github.com/helium/wallet-app/assets/84670450/8e48653f-b910-46da-8df2-427c96afcd48)
![wild chambray last week](https://github.com/helium/wallet-app/assets/84670450/7737b943-21fb-4ed8-8101-ae81aa96e218)

**Comment by Australian-Hnt-collectors** [comment] 2023-07-04 00:32
> @madninja I'm transferring this to the oracles repo. Can't find any issues on the wallet app that would cause this, nor our API. Maybe something with the oracle code writing to the database?

If you check the various fb pages and communities they are all having claiming issues

**Comment by madninja** [comment] 2023-07-04 18:45
> > @madninja I'm transferring this to the oracles repo. Can't find any issues on the wallet app that would cause this, nor our API. Maybe something with the oracle code writing to the database?
> 
> If you check the various fb pages and communities they are all having claiming issues, Many do not know how to use github however it is there

Could you be a bit more specific? Most claiming issues were claiming itself failing vs mismatch between what other sites report vs what appears as claimable in the wallet app. More links would maybe help

**Comment by Australian-Hnt-collectors** [comment] 2023-07-05 01:52
@madninja not sure how much more i can be specific obviously i have the issue and if you check the different helium facebook pages community members having an issue, we have spent nearly two months discussing this with Mike V and he has re opened this a few times now as its still an issue. the rewards that are claimable do not match what people are being told they are earning. often a few times people cannot claim at all or they press claim and do not get the rewards as per the facebook posts

**Comment by madninja** [comment] 2023-07-05 01:55
> @madninja not sure how much more i can be specific obviously i have the issue and if you check the different helium facebook pages community members having an issue, we have spent nearly two months discussing this with Mike V and he has re opened this a few times now as its still an issue. the rewards that are claimable do not match what people are being told they are earning. often a few times people cannot claim at all or they press claim and do not get the rewards as per the facebook posts

Asking for some links to these various Facebook pages to have more samples to work with

**Comment by Australian-Hnt-collectors** [comment] 2023-07-05 02:03
> > @madninja not sure how much more i can be specific obviously i have the issue and if you check the different helium facebook pages community members having an issue, we have spent nearly two months discussing this with Mike V and he has re opened this a few times now as its still an issue. the rewards that are claimable do not match what people are being told they are earning. often a few times people cannot claim at all or they press claim and do not get the rewards as per the facebook posts
> 
> Asking for some links to these various Facebook pages to have more samples to work with

https://www.facebook.com/groups/191114902844198 scroll down and find the issues.  https://www.facebook.com/groups/818497522348684 second post down talks about losing IOT when claiming. there are others as well

**Comment by jeffgrunewald** [comment] 2023-07-12 13:55
@Australian-Hnt-collectors is this problem still happening for Wild Chambray Octopus (112nE6SSZJHATKSLGCnFjTeJXrFp7LZM4N5fusmW1dSX6SEdmpJo) as of the last reward distribution ending at 1:00 UTC on 7/12? I am showing reward shares in the bucket feeding the hotspot's wallet for the last 4 consecutive days.

**Comment by jeffgrunewald** [comment] 2023-07-12 14:24
we're also showing the rewards for that hotspot were last updated at the same time (`2023-07-12T01:00:00+00`) which means the solana program has updated rewards linked to the hotspot that should be redeemable. if you're still seeing this issue that would indicate the problem is further downstream, either in the solana program managing distributions or indeed in the wallet app

**Comment by Australian-Hnt-collectors** [comment] 2023-07-12 22:12
> we're also showing the rewards for that hotspot were last updated in the foundation's reward index database at the same time (`2023-07-12T01:00:00+00`) which means the solana program has updated rewards linked to the hotspot that should be redeemable. if you're still seeing this issue that would indicate the problem is further downstream, either in the solana program managing distributions or indeed in the wallet app

the Australian community is seeing a lot of this happening, this was first reported as a wallet app issue but has been kicked around for months now as a hot potato issue that no one seems to want to look at bud.

**Comment by jeffgrunewald** [comment] 2023-07-12 22:25
Understandably frustrating but we’ve now validated the data agrees with your assessment up to and including the end of the Oracles’ poc reward pipeline and while I don’t think we have insight into how Helium Geek/Tracker have implemented their analysis, they’re basing their view of your reward activity on the same data. @ChewingGlass given the above, this issue needs to be debugged further downstream of the oracles

**Comment by ChewingGlass** [comment] 2023-07-13 16:15
@jeffgrunewald I'm showing 40765452098 iot lifetime rewards for this hotspot in the rewards index. 
40765452098 on chain

https://explorer.solana.com/address/63hH9kwpCfHZfRkcDCGeHDopg3KMEru1sWYG5dWBckdY/anchor-account

Rewards are being actively claimed for the hotspot. I can see successful transactions. 

Further, you can see txs like

https://explorer.solana.com/tx/2LYFB6Cr8pL2VXhgr3jts3cA9vqmsaQGXprK3SQdgRa9KVVDxTmYTkmMN3kFjbWPNvho1tiuwt6TZBtY3XBsVH3U

Where 98apFPNnj5D18vjjgJ5XhiV4eELdPT8V6avcqijVnu9G is claiming IOT rewards as expected.


On Solscan you can see a healthy history of claiming IOT.
https://solscan.io/account/98apFPNnj5D18vjjgJ5XhiV4eELdPT8V6avcqijVnu9G#splTransfers

What's the issue here? This issue reports IOT is not showing up in the wallet, but I can verify that the wallet does in fact have the IOT for this hotspot. @Australian-Hnt-collectors am I missing something? Is this just not one of the hotspots affected?

**Comment by ChewingGlass** [comment] 2023-07-13 16:58
Here's what I _think_ might be happening. There was a bug that will be fixed in the next wallet app release that caused tx history not to show up on token accounts. https://github.com/helium/wallet-app/issues/372

My guess is that people were claiming IOT, and then clicking on their IOT account to see the inflow transaction. While the balance may have changed, IOT numbers have a high supply so it's hard to notice. When users went to check for history, they saw no inflow transactions and so assumed there was no IOT claimed. 

@Australian-Hnt-collectors does this sound like a plausible explanation? If not, can you give a hotspot address that is experiencing this problem?

**Comment by Australian-Hnt-collectors** [comment] 2023-07-13 22:57
> Here's what I _think_ might be happening. There was a bug that will be fixed in the next wallet app release that caused tx history not to show up on token accounts. [helium/wallet-app#372](https://github.com/helium/wallet-app/issues/372)
> 
> My guess is that people were claiming IOT, and then clicking on their IOT account to see the inflow transaction. While the balance may have changed, IOT numbers have a high supply so it's hard to notice. When users went to check for history, they saw no inflow transactions and so assumed there was no IOT claimed.
> 
> @Australian-Hnt-collectors does this sound like a plausible explanation? If not, can you give a hotspot address that is experiencing this problem?

We have claimed yes within the last few weeks of this month, however for the months prior to claiming as explained for weeks and MONTHS we were discussing this problem with MIKE V and Sophi whom saw the issue and could not explain it. now we made a git hub about it and it was closed then opened again and again kicked around and moved which was obviously a play for time to try and get a fix going for this issue rather than admitting it was an issue.  As a hosting company and this is our test account wild chambray octopus when we roll out more and more sensors of different types. now we have to under the obligation to our hosts and also to our company tax reporting requirements AKA  every four months in Australia compile the stats of said unit and provide our hosts with a activity statement this is called a quarterly earning statement legally required But we experienced the same thing also on Wild Chambray as we did on Cheery Blush Baboon wallet and other units, Other people experienced the same, again this was raised weeks and months before we posted it in git hub with Mike V 
Just the same as many Australians did not get our genesis coins but lets not talk about that moment lets quietly side step those moments, this has been going on SINCE BEFORE MAY. when we made this github it was at the request of MIKE V who could not explain what was going on.  Other people have seen the same, I have posted links to those fb comments no longer are Australians willing to do all the work for Helium as we had been doing previously as for weeks and months we were not listened to even when we provided facts till they came out of our head all we had was the bullshit of can you provide a link or give us more, No we cannot anymore and will not sorry not taking it all out on you @ChewingGlass but seriously this has been a joke no wonder why in Australia people are turning to things IX or other reliable systems bud..

**Comment by ChewingGlass** [comment] 2023-07-14 14:58
I apologize, the migration was a monumental undertaking and we've been trying to hammer out the bugs for the past few months.

Is this issue resolved? I realize it was not working for a while, but is it working now? I can't debug without something that is currently broken to diagnose.

**Comment by Australian-Hnt-collectors** [comment] 2023-07-15 00:33
> I apologize, the migration was a monumental undertaking and we've been trying to hammer out the bugs for the past few months.
> 
> Is this issue resolved? I realize it was not working for a while, but is it working now? I can't debug without something that is currently broken to diagnose.

its working now for me but others around Australia has the issue

**Comment by ChewingGlass** [comment] 2023-07-17 22:06
I'm going to close the issue for now. If you see anyone else who has the issue, point them here. If they can give a wallet/hotspot I'll dig into it and re open.

**Closed by ChewingGlass** 2023-07-17 22:06 UTC
Labels: bug

**Comment by Australian-Hnt-collectors** [comment] 2023-07-18 00:08
> I'm going to close the issue for now. If you see anyone else who has the issue, point them here. If they can give a wallet/hotspot I'll dig into it and re open.

Easy to close shit so you dont have to fix it, told you before not doing your work anymore do it yourself maybe fix your stuff first

**Comment by BuddyCarlos** [comment] 2023-07-25 11:02
@ChewingGlass I believe I have the same issue. I have had nothing but dramas since the new update. I am using Heliumgeek to monitor my hotspot tall teal fox in Hillarys Australia and it’s not reflective to what’s in my account. 
I make a rewards claim but it does not show up in my wallet. I have enough Sol. I have reset everything onboarded again. And it’s nearly impossible to get a Helium support staff.  Any help would be greatly appreciated.

**Comment by BuddyCarlos** [comment] 2023-07-25 11:07
My address 
3ijrAKYuzNn6pcdt2XmDDRVarQbTxV1quD53sgjXmcLn


My hotspot 
11agQPGruCtCc6tf89gGsTJ5cYHv5ifrv4P8wWC2yYwzRvRrXVJ

**Comment by ChewingGlass** [comment] 2023-07-25 16:16
Thanks @BuddyCarlos that's very helpful information. I'm looking at this hotspot on Helium Geek. I show 8.9k rewards over the last 30 days. Looking on chain, I'm seeing 6 hours ago all 8.9k IOT were claimed. 

https://explorer.solana.com/tx/2hwV4XVu3uVvJCMaz4S1ZPGdR3z8r2aWuiChLwTdR3KQJtMCGSWWKkSu5HLQfnThdwgCaZzP55RDF1HM1dFM2jks

It seems like you were having an issue but later figured it out? Are you able to share what's happened?

**Comment by Australian-Hnt-collectors** [comment] 2023-07-25 23:11
> Thanks @BuddyCarlos that's very helpful information. I'm looking at this hotspot on Helium Geek. I show 8.9k rewards over the last 30 days. Looking on chain, I'm seeing 6 hours ago all 8.9k IOT were claimed.
> 
> https://explorer.solana.com/tx/2hwV4XVu3uVvJCMaz4S1ZPGdR3z8r2aWuiChLwTdR3KQJtMCGSWWKkSu5HLQfnThdwgCaZzP55RDF1HM1dFM2jks
> 
> It seems like you were having an issue but later figured it out? Are you able to share what's happened?

So just going to keep it closed still or re open it now others are coming forward with same problem

**Comment by Spewdog50** [comment] 2024-02-28 21:23
Hi team, I seem to be experiencing what could be similar issue. Energetic Indigo Weasel. 
since last reward claim miner seems to be online and still producing IOT as per relay/HeliumGeek etc but I have 0 rewards to claim. 

This isn’t an issue with claiming but it shows 0 to claim.
